server:
  port: 8080

spring:
  profile: dev
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/contact_info
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: INFO
