server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: true   # ✅ Required for HTTPS
        http-only: true
        same-site: None  # ✅ Required for cross-origin cookies

spring:
  datasource:
#    url: jdbc:postgresql://monorail.proxy.rlwy.net:12868/railway
#    username: postgres
#    password: MUeAsaxOSnvamWpVMNzvUhmAoNnBhXRy
    url: jdbc:postgresql://localhost:5432/railway
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


logging:
  level:
    org.springframework.security: DEBUG